# This dependabot check if there are a new version of package, is not security update
version: 2
updates:
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(composer): "
    groups:
      composer-security:
        applies-to: security-updates
        update-types:
          - major
          - minor
          - patch
      composer-version:
        applies-to: version-updates
        update-types:
          - major
          - minor
          - patch

  - package-ecosystem: "docker" # See documentation for possible values
    directories:
      - "/"
      - "/.docker/frankenphp"
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(docker): "
    groups:
      docker-security:
        applies-to: security-updates
        update-types:
          - major
          - minor
          - patch
      docker-version:
        applies-to: version-updates
        update-types:
          - major
          - minor
          - patch

  - package-ecosystem: "docker-compose" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(docker compose): "
    groups:
      docker-security:
        applies-to: security-updates
        update-types:
          - major
          - minor
          - patch
      docker-version:
        applies-to: version-updates
        update-types:
          - major
          - minor
          - patch

  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/.github" # Location of package manifests
    schedule:
      interval: "monthly"
    commit-message:
      prefix: "chore(gha): "
    groups:
      docker-security:
        applies-to: security-updates
        update-types:
          - major
          - minor
          - patch
      docker-version:
        applies-to: version-updates
        update-types:
          - major
          - minor
          - patch
